FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 8051

COPY . .

CMD ["streamlit", "run", "tree_interactive_viz.py"]

# sudo docker build -t front:v0 .
# sudo docker run -d --restart unless-stopped -v /home/roman/project/hack-digit-rosatom-my-voice:/app/data -p 8051:8051 front_cp2:v0